name: 'Changelog from GitHub Releases'
description: 'Generate CHANGELOG.md from GitHub Releases'
author: 'ricardoboss'

branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  file:
    description: 'Where to write the CHANGELOG.md file'
    required: true
    default: './CHANGELOG.md'

runs:
  using: node20
  main: dist/index.js
