name: 'Changelog from GitHub Releases'
description: 'Generate CHANGELOG.md from GitHub Releases'
author: 'ricardoboss'

branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  file:
    description: 'Where to write the CHANGELOG.md file'
    required: true
    default: './CHANGELOG.md'
  repository:
    description: 'The repository to get the releases from (default: owner/repo)'
    required: false
    default: '${{ github.repository }}'
  token:
    description: 'The GitHub token to use for authentication'
    required: true
    default: '${{ github.token }}'
  prerelease:
    description: 'Whether to include pre-releases'
    required: false
    default: 'false'

outputs:
  changelog:
    description: 'The generated change log'

runs:
  using: node20
  main: dist/index.js
